name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg
    - name: Create Test Media
      run: sh tests/create_test_media.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
