name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Install ffmpeg
#       run: sudo apt-get install ffmpeg
    - name: Create Test Media
      run: cd tests; sh create_test_media.sh
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
#     - name: rust-tarpaulin
#       uses: actions-rs/tarpaulin@v0.1.0
